name: guardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_background_video_recorder: ^1.0.0+2
  shake: ^3.0.0
  shared_preferences: ^2.5.3
  sensors_plus: 6.1.1  
  permission_handler: ^12.0.0+1  
  path_provider: ^2.0.11  
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  # flutter_sms: ^2.3.3
  sms_mms: ^0.0.3
  # telephony: ^0.2.0
  another_telephony: ^0.4.1
  # flutter_sms: ^2.3.3
  # geolocator: any
  # flutter_foreground_task: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
